/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                headline: ['Manrope'],
                body: ['Inter'],
                label: ['Inter'],
            },
            colors: {
                'secondary-fixed': '#e0e0ff',
                'on-error-container': '#93000a',
                'on-surface': '#1c1b1b',
                surface: '#fcf9f8',
                primary: '#b7000c',
                'inverse-on-surface': '#f3f0ef',
                'secondary-fixed-dim': '#bdc2ff',
                'on-tertiary-container': '#f9f8ff',
                'error': '#ba1a1a',
                'surface-container-highest': '#e5e2e1',
                'inverse-surface': '#313030',
                'on-primary-fixed-variant': '#930007',
                secondary: '#4c56af',
                'surface-variant': '#e5e2e1',
                'primary-fixed-dim': '#ffb4aa',
                outline: '#946e69',
                'on-tertiary-fixed-variant': '#00458f',
                'surface-dim': '#dcd9d9',
                'surface-container-lowest': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-surface-variant': '#5f3f3b',
                tertiary: '#0058b2',
                'error-container': '#ffdad6',
                background: '#fcf9f8',
                'on-primary-container': '#fff7f6',
                'on-secondary': '#ffffff',
                'primary-fixed': '#ffdad5',
                'on-background': '#1c1b1b',
                'on-tertiary-fixed': '#001b3f',
                'tertiary-container': '#0070e0',
                'surface-bright': '#fcf9f8',
                'tertiary-fixed-dim': '#abc7ff',
                'on-secondary-fixed-variant': '#343d96',
                'on-primary-fixed': '#410001',
                'outline-variant': '#e9bcb6',
                'surface-container-high': '#ebe7e7',
                'primary-container': '#e60012',
                'tertiary-fixed': '#d7e3ff',
                'surface-tint': '#c0000d',
                'surface-container-low': '#f6f3f2',
                'on-secondary-fixed': '#000767',
                'surface-container': '#f0edec',
                'on-primary': '#ffffff',
                'on-secondary-container': '#27308a',
                'inverse-primary': '#ffb4aa',
                'secondary-container': '#959efd',
                'on-error': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
